version: 2.1
jobs:
  nbdev-tests:
    resource_class: xlarge
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            conda install mamba -n base -c conda-forge
            mamba create -n neuralforecast python=3.7
            conda init bash
            source ~/.bashrc
            conda activate neuralforecast
            mamba env update -f environment.yml
      - run:
          name: Run nbdev tests
          command: |
            conda init bash
            source ~/.bashrc
            conda activate neuralforecast
            pip install ./
            nbdev_test --do_print --timing --n_workers 1
  test-model-performance:
    resource_class: xlarge
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            conda install mamba -n base -c conda-forge
            mamba create -n neuralforecast python=3.7
            conda init bash
            source ~/.bashrc
            conda activate neuralforecast
            mamba env update -f environment.yml
      - run:
          name: Run model performance tests
          command: |
            conda init bash
            source ~/.bashrc
            conda activate neuralforecast
            pip install -e ".[dev]"
            cd ./action_files/test_models/
            pip install -r requirements.txt
            python -m src.models
            python -m src.evaluation
            cd ../../
      - store_artifacts:
          path: ./action_files/test_models/data/evaluation.csv
          destination: evaluation.csv
  test-gpu-pipeline:
    resource_class: gpu.nvidia.small
    machine:
      - image: ubuntu-2004-cuda-11.4:202110-01
    steps:
      - run:
          name: Install dependencies
          command: |
            conda install mamba -n base -c conda-forge
            mamba create -n neuralforecast python=3.7
            conda init bash
            source ~/.bashrc
            conda activate neuralforecast
            pip install ./
      - run:
          name: Run gpu tests
          command: |
            conda init bash
            source ~/.bashrc
            conda activate neuralforecast
            pip install ./
            python -m src.gpu_pipeline

workflows:
  sample:
    jobs:
      - nbdev-tests
      - test-model-performance
