project:
  type: website
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  sidebar:
    style: floating
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/nixtla/neuralforecast/issues
          - text: "Join our Slack"
            icon: chat-right-text
            href: https://join.slack.com/t/nixtlaworkspace/shared_invite/zt-135dssye9-fWTzMpv2WBthq8NK0Yvu6A
    right:
      - icon: github
        href: "https://github.com/nixtla/neuralforecast"
      - icon: twitter
        href: https://twitter.com/nixtlainc
        aria-label: Nixtla Twitter

metadata-files: [nbdev.yml, sidebar.yml]
