name: neuralforecast
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - hyperopt
  - matplotlib
  - numba
  - pandas
  - pip
  - pytorch
  - cpuonly
  - requests
  - statsmodels
  - scikit-learn
  - tqdm
  - xlrd
  - openpyxl
  - pip:
    - nbdev==1.1.23
    - pytorch-lightning>=1.3.0
    - torchinfo
    - py7zr
    - gdown
    - pytest-cov
