name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          mamba-version: "*"
          channels: pytorch,conda-forge,defaults
          channel-priority: true
          activate-environment: neuralforecast
          environment-file: action_files/environment.yml
          use-only-tar-bz2: true

      - name: Install library
        shell: bash -l {0}
        run: pip install -e .

      - name: Run coverage
        shell: bash -l {0}
        run: pytest action_files/test_nbs.py --cov=neuralforecast --cov-report xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          files: coverage.xml
        
